name:                countwordsHS
version:             0.1.0.0
github:              "githubuser/countwordsHS"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/countwordsHS#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- streamly >= 0.8.1.1 && < 0.8.2
- fusion-plugin
- unordered-containers
- vector
- vector-hashtables
- primitive
- bytestring
- streaming
- streaming-bytestring
- clutter
- finite
- hashable
- radix-tree

library:
  source-dirs: src

executables:
  LazyMap:
    main:                LazyMap.hs
    source-dirs:         LazyMap
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  LazyHMRef:
    main:                LazyHMRef.hs
    source-dirs:         LazyHMRef
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  LazyVH:
    main:                LazyVH.hs
    source-dirs:         LazyVH
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  StreamlyHMRef:
    main:                StreamlyHMRef.hs
    source-dirs:         StreamlyHMRef
    ghc-options:
    - -rtsopts
    - -O2
    - -fdicts-strict
    - -fmax-worker-args=16
    - -fspec-constr-recursive=16
    - -fplugin Fusion.Plugin
    dependencies:
    - countwordsHS

  StreamlyThreadedHMRef:
    main:                StreamlyHMRef.hs
    source-dirs:         StreamlyHMRef
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fdicts-strict
    - -fmax-worker-args=16
    - -fspec-constr-recursive=16
    - -fplugin Fusion.Plugin
    dependencies:
    - countwordsHS

  StreamlyVH:
    main:                StreamlyVH.hs
    source-dirs:         StreamlyVH
    ghc-options:
    - -rtsopts
    - -O2
    - -fdicts-strict
    - -fmax-worker-args=16
    - -fspec-constr-recursive=16
    - -fplugin Fusion.Plugin
    dependencies:
    - countwordsHS

  LinewiseVH:
    main:                LinewiseVH.hs
    source-dirs:         LinewiseVH
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  LinewiseClutter:
    main:                LinewiseClutter.hs
    source-dirs:         LinewiseClutter
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  BufwiseClutter:
    main:                BufwiseClutter.hs
    source-dirs:         BufwiseClutter
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  BufwiseFiniteBS:
    main:                BufwiseFiniteBS.hs
    source-dirs:         BufwiseFiniteBS
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  StreamingHMBS:
    main:                StreamingHMBS.hs
    source-dirs:         StreamingHMBS
    ghc-options:
    - -rtsopts
    - -O2

  LazyHMBS:
    main:                LazyHMBS.hs
    source-dirs:         LazyHMBS
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - countwordsHS

  BufwiseVHBS:
    main:                BufwiseVHBS.hs
    source-dirs:         BufwiseVHBS
    ghc-options:
    - -rtsopts
    - -O2



# tests:
#   simple-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - simple
